### ISSUE TITLE
Eslint and Stylelint coding standards on github workflows?

### ISSUE THREAD

**Issue by millnut** [localgovdrupal/localgov_shared_workflows#10]
Now that shared workflows are on all modules, do we want to consider setting up eslint checks (for js files) and stylelint checks (for css files) so we are aligned with Drupal's coding standards for these? We currently use Drupal coding standards for PHP related files so aligning on the JS/CSS side as well would help with consistency.

@markconroy would be good to get your thoughts on this?

**Comment by markconroy** [comment]
Yes, I think this is a great idea. 

We do have stylelint in the localgov_base theme, but you need to manually run it, which only happens periodically.

We have no eslint for JS files.

**Comment by millnut** [comment]
Closing as this has now been merged
