### ISSUE TITLE
Test fail on alert banner as target to 1.8.x can't be resolved to a set of dependencies

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_shared_workflows#3]
See https://github.com/localgovdrupal/localgov_alert_banner/actions/runs/9872131554/job/27261593508?pr=346

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
> Error: Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - localgovdrupal/localgov is locked to version 3.x-dev and an update of this package was not requested.
>     - localgovdrupal/localgov 3.x-dev requires localgovdrupal/localgov_alert_banner ^1.2.0 -> found localgovdrupal/localgov_alert_banner[1.2.0, ..., 1.x-dev] but it conflicts with your root composer.json require (dev-fix/345-add-banner-type-accessible-name as 1).
> 
>     - localgovdrupal/localgov is locked to version 3.x-dev and an update of this package was not requested.
>     - localgovdrupal/localgov 3.x-dev requires localgovdrupal/localgov_alert_banner ^1.2.0 -> found localgovdrupal/localgov_alert_banner[1.2.0, ..., 1.x-dev] but it conflicts with your root composer.json require (dev-fix/345-add-banner-type-accessible-name as 1).

I think it's getting confused with the 1.8.x.

**Comment by millnut** [comment]
Yep I think it's related to the previous steps on how it works out which env vars to set.

**Working**
```bash
env:
  GIT_BASE: 1.x
  GIT_BRANCH: 1-8-refactor
  HEAD_USER: localgovdrupal
  COMPOSER_REF: dev-1-8-refactor
  LATEST_RELEASE: 1.7.8
  COMPOSER_PROCESS_TIMEOUT: 0
  COMPOSER_NO_INTERACTION: 1
  COMPOSER_NO_AUDIT: 1
```

```bash
  env:
    GIT_BASE: 1.8.x
    GIT_BRANCH: 1.8.x
    HEAD_USER: localgovdrupal
    COMPOSER_REF: 1.8.x-dev
    LATEST_RELEASE: 1
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    COMPOSER_NO_AUDIT: 1
```

**Not working**
```bash
env:
  GIT_BASE: 1-8-refactor
  GIT_BRANCH: 1-8-refactor
  HEAD_USER: localgovdrupal
  COMPOSER_REF: dev-1-8-refactor
  LATEST_RELEASE: 1
  COMPOSER_PROCESS_TIMEOUT: 0
  COMPOSER_NO_INTERACTION: 1
  COMPOSER_NO_AUDIT: 1
```

```bash
  env:
    GIT_BASE: 1.8.x
    GIT_BRANCH: fix/345-add-banner-type-accessible-name
    HEAD_USER: localgovdrupal
    COMPOSER_REF: dev-fix/345-add-banner-type-accessible-name
    LATEST_RELEASE: 1
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    COMPOSER_NO_AUDIT: 1
```

I believe it's due to `GIT_BASE` and `LATEST_RELEASE` which is used in composer which is causing the issues, I'll do some debugging when I have some time on how it gets the latest release values.

**Comment by millnut** [comment]
Closing as this has been fixed by https://github.com/localgovdrupal/localgov_shared_workflows/pull/4
